"""empty message

Revision ID: 35e8caaf61b0
Revises: ee32a5858ef3
Create Date: 2026-02-20 10:15:33.290891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35e8caaf61b0'
down_revision = 'ee32a5858ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_pfp_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_pfp_url', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
