"""empty message

Revision ID: 902261a5dc8a
Revises: 96c98229d6e1
Create Date: 2026-02-04 09:40:04.449241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902261a5dc8a'
down_revision = '96c98229d6e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('genres', sa.String(), nullable=False),
    sa.Column('publisher', sa.String(), nullable=False),
    sa.Column('developer', sa.String(), nullable=False),
    sa.Column('cover_link', sa.String(), nullable=True),
    sa.Column('release_date', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backloglist', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'games', ['game_id'], ['id'])

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'games', ['game_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('backloglist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('games')
    # ### end Alembic commands ###
